### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by kungfoo**

### CODE REVIEW

**Comment by wolfie** [comment]
Refresher is intended to be attached to the UI, therefore UI.addExtension() is preferred.

**Comment by kungfoo** [comment]
I do not necessarily agree, in our project we want to, for instance, refresh a table with new contents and not the entire UI.

**Comment by wolfie** [comment]
Since adding several active Refreshers at once within a view has high probabilities to affect the performance of your application, I like the API to make such mistakes difficult. This might require manual implementations of additional event handling with deep nesting, but you get some you lose some. 

In any case, Refresher is becoming deprecated due to [integrated polling in Vaadin 7.1](https://vaadin.com/wiki/-/wiki/Main/Using%20polling), so you probably want to start using that instead in any case.

**Comment by wolfie** [comment]
As an added comment, yes, this could be worked around by having a global refresher with instances accessing it, but it's more rework than I want to put into the Refresher, especially with the integration of a similar functionality

**Pull request closed without merging**
